import { TSeasons } from "./type";
export const seasons:TSeasons = {
  winter: {
    closeProjects: 10,
    income: 600000,
    hired: 10,
    dismissed: 10,
    newProjects: 10,
  },
  spring: {
    closeProjects: 10,
    income: 750000,
    hired: 10,
    dismissed: 10,
    newProjects: 10,
  },
  summer: {
    closeProjects: 10,
    income: 550000,
    hired: 10,
    dismissed: 10,
    newProjects: 10,
  },
  autumn: {
    closeProjects: 10,
    income: 900000,
    hired: 10,
    dismissed: 10,
    newProjects: 10,
  },
};

// let hireds: TSeasons[] = [
//   {
//     name: "John",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "Alice",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Michael",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
//   {
//     name: "Emma",
//     departament: "TECH",
//     experience: 2,
//     isClosedProjects: true,
//     salary: 350000,
//   },
//   {
//     name: "David",
//     departament: "DESIGN",
//     experience: 4,
//     isClosedProjects: false,
//     salary: 500000,
//   },
//   {
//     name: "Sophia",
//     departament: "PROJECT",
//     experience: 5,
//     isClosedProjects: true,
//     salary: 600000,
//   },
//   {
//     name: "James",
//     departament: "TECH",
//     experience: 0,
//     isClosedProjects: false,
//     salary: 200000,
//   },
//   {
//     name: "Olivia",
//     departament: "DESIGN",
//     experience: 8,
//     isClosedProjects: true,
//     salary: 900000,
//   },
//   {
//     name: "Daniel",
//     departament: "PROJECT",
//     experience: 6,
//     isClosedProjects: false,
//     salary: 700000,
//   },
//   {
//     name: "Emily",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "William",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Ava",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
//   {
//     name: "Alexander",
//     departament: "TECH",
//     experience: 2,
//     isClosedProjects: true,
//     salary: 350000,
//   },
//   {
//     name: "Mia",
//     departament: "DESIGN",
//     experience: 4,
//     isClosedProjects: false,
//     salary: 500000,
//   },
//   {
//     name: "Benjamin",
//     departament: "PROJECT",
//     experience: 5,
//     isClosedProjects: true,
//     salary: 600000,
//   },
//   {
//     name: "Charlotte",
//     departament: "TECH",
//     experience: 0,
//     isClosedProjects: false,
//     salary: 200000,
//   },
//   {
//     name: "Henry",
//     departament: "DESIGN",
//     experience: 8,
//     isClosedProjects: true,
//     salary: 900000,
//   },
//   {
//     name: "Elijah",
//     departament: "PROJECT",
//     experience: 6,
//     isClosedProjects: false,
//     salary: 700000,
//   },
//   {
//     name: "Scarlett",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "Lucas",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Victoria",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
// ];

// let hireds: TSeasons[] = [
//   {
//     name: "John",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "Alice",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Michael",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
//   {
//     name: "Emma",
//     departament: "TECH",
//     experience: 2,
//     isClosedProjects: true,
//     salary: 350000,
//   },
//   {
//     name: "David",
//     departament: "DESIGN",
//     experience: 4,
//     isClosedProjects: false,
//     salary: 500000,
//   },
//   {
//     name: "Sophia",
//     departament: "PROJECT",
//     experience: 5,
//     isClosedProjects: true,
//     salary: 600000,
//   },
//   {
//     name: "James",
//     departament: "TECH",
//     experience: 0,
//     isClosedProjects: false,
//     salary: 200000,
//   },
//   {
//     name: "Olivia",
//     departament: "DESIGN",
//     experience: 8,
//     isClosedProjects: true,
//     salary: 900000,
//   },
//   {
//     name: "Daniel",
//     departament: "PROJECT",
//     experience: 6,
//     isClosedProjects: false,
//     salary: 700000,
//   },
//   {
//     name: "Emily",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "William",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Ava",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
//   {
//     name: "Alexander",
//     departament: "TECH",
//     experience: 2,
//     isClosedProjects: true,
//     salary: 350000,
//   },
//   {
//     name: "Mia",
//     departament: "DESIGN",
//     experience: 4,
//     isClosedProjects: false,
//     salary: 500000,
//   },
//   {
//     name: "Benjamin",
//     departament: "PROJECT",
//     experience: 5,
//     isClosedProjects: true,
//     salary: 600000,
//   },
//   {
//     name: "Charlotte",
//     departament: "TECH",
//     experience: 0,
//     isClosedProjects: false,
//     salary: 200000,
//   },
//   {
//     name: "Henry",
//     departament: "DESIGN",
//     experience: 8,
//     isClosedProjects: true,
//     salary: 900000,
//   },
//   {
//     name: "Elijah",
//     departament: "PROJECT",
//     experience: 6,
//     isClosedProjects: false,
//     salary: 700000,
//   },
//   {
//     name: "Scarlett",
//     departament: "TECH",
//     experience: 3,
//     isClosedProjects: true,
//     salary: 400000,
//   },
//   {
//     name: "Lucas",
//     departament: "DESIGN",
//     experience: 1,
//     isClosedProjects: false,
//     salary: 250000,
//   },
//   {
//     name: "Victoria",
//     departament: "PROJECT",
//     experience: 7,
//     isClosedProjects: true,
//     salary: 800000,
//   },
// ];
